name: Call OpenAI API

on:
  workflow_dispatch:
    inputs:
      question:
        description: 'Question for OpenAI'
        required: true
        default: 'What is the capital of France?'

jobs:
  ask_openai:
    runs-on: ubuntu-latest
    outputs:
      answer: ${{ steps.get_answer.outputs.response }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install openai

      - name: Get answer from OpenAI
        id: get_answer
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_AI }}
        run: |
          node -e "
          const OpenAI = require('openai');
          const openai = new OpenAI({
            baseURL: 'https://models.inference.ai.azure.com',
            apiKey: process.env.GITHUB_TOKEN
          });

          (async () => {
            const response = await openai.chat.completions.create({
              messages: [{role:'user', content:'${{ github.event.inputs.question }}'}],
              model: 'gpt-4o',
              temperature: 1,
              max_tokens: 4096,
              top_p: 1
            });
            const answer = response.choices[0].message.content;
            console.log('answer=' + JSON.stringify(answer));
          })();
          " >> $GITHUB_OUTPUT
