name: OpenAI Query

on:
  workflow_dispatch:
    inputs:
      question:
        description: "User's question"
        required: true

jobs:
  ask_openai:
    runs-on: ubuntu-latest
    outputs:
      ai_response: ${{ steps.openai_step.outputs.ai_response }}  # ✅ Store response as output

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ask OpenAI
        id: openai_step  # ✅ Assign an ID so we can reference the output
        run: |
          RESPONSE=$(curl -X POST "https://models.inference.ai.azure.com/chat/completions" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "gpt-4o",
            "messages": [
              { "role": "system", "content": "You are a helpful AI assistant." },
              { "role": "user", "content": "${{ github.event.inputs.question }}" }
            ],
            "temperature": 1,
            "max_tokens": 4096,
            "top_p": 1
          }' | jq -r '.choices[0].message.content')  # ✅ Extract response text

          echo "ai_response=$RESPONSE" >> "$GITHUB_OUTPUT"  # ✅ Store response using Environment File
          echo $RESPONCE
